# Generated by Django 5.2.17 on 2026-08-28 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('reg_no', models.CharField(blank=True, default='', max_length=255)),
                ('reg_date', models.CharField(blank=True, default='', max_length=20)),
                ('ar_no', models.CharField(blank=True, default='', max_length=255)),
                ('budget', models.CharField(blank=True, default='', max_length=255)),
                ('actual_expenditure', models.CharField(blank=True, default='', max_length=255)),
                ('contractor', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.CharField(blank=True, default='', max_length=20)),
                ('completion_date', models.CharField(blank=True, default='', max_length=20)),
                ('target_etc', models.CharField(blank=True, default='', max_length=255)),
                ('area_unit', models.CharField(blank=True, default='', max_length=255)),
                ('project_category', models.CharField(blank=True, default='', max_length=255)),
                ('nature_of_project', models.CharField(blank=True, default='', max_length=255)),
                ('projected_savings', models.CharField(blank=True, default='', max_length=255)),
                ('irr', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='portal.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('employee_id', models.CharField(blank=True, default='', max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='portal.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('planned_start', models.CharField(blank=True, default='', max_length=20)),
                ('planned_finish', models.CharField(blank=True, default='', max_length=20)),
                ('duration', models.IntegerField(default=1)),
                ('actual_start', models.CharField(blank=True, default='', max_length=20)),
                ('actual_finish', models.CharField(blank=True, default='', max_length=20)),
                ('criticality_rating', models.IntegerField(default=1)),
                ('status', models.CharField(default='Planned', max_length=50)),
                ('progress_pct', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='portal.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, verbose_name='Tag Number / Name')),
                ('category', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=1)),
                ('custom_params', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='portal.project')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('project', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(max_length=100)),
                ('status', models.CharField(default='Not Applicable', max_length=50)),
                ('date', models.CharField(blank=True, default='N/A', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='portal.project')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('project', 'approval_type')},
            },
        ),
    ]
