"""
Deterministic analytics engine.

Everything the dashboard displays as a *number* is computed here, in plain Python,
from the rows in the database. Nothing in this module calls an external service and
nothing here is generated by a language model. That separation is deliberate:

    analytics.py   -> computes the facts   (deterministic, testable, always available)
    ai_insights.py -> writes about them    (optional narrative layer on top)

So if the AI layer is disabled, offline, rate-limited or misconfigured, the dashboard
still renders every metric, both S-curves and the full critical-activity ranking.

--------------------------------------------------------------------------------
S-curve methodology
--------------------------------------------------------------------------------
A project's progress is modelled as weighted activity completion, where each
activity's weight is its planned duration in days (min 1). Duration is used as the
weight because it is the closest proxy for work content available in the schema --
a 30-day activity represents more of the project than a 2-day one. Cancelled
activities are excluded from both curves entirely so they don't depress progress.

  Target (planned) curve
      For each activity, planned completion ramps linearly from planned_start to
      planned_finish. Cumulative planned % at date d is the weighted mean of those
      per-activity fractions. This is the baseline the project committed to.

  Current (actual) curve
      Completed  -> ramps linearly from actual_start to actual_finish, 100% after.
      In Progress / Delayed -> ramps linearly from actual_start to today, reaching
                               the recorded progress_pct at today.
      Planned / not started  -> 0%.
      The actual curve is truncated at today, since there is no such thing as
      actual progress in the future. This is what produces the familiar picture of
      the actual line stopping short of the planned line.

Schedule variance = actual % at today - planned % at today, expressed in percentage
points. Negative means behind schedule. The Schedule Performance Index (SPI) is the
ratio actual/planned, where 1.0 is exactly on plan.
"""

from __future__ import annotations

from datetime import date, datetime, timedelta

from . import constants

# Date formats accepted when parsing the CharField date columns. The portal writes
# ISO first; the others are tolerated because hand-entered sheets vary.
_DATE_FORMATS = ("%Y-%m-%d", "%d-%m-%Y", "%d/%m/%Y", "%Y/%m/%d", "%d.%m.%Y", "%d.%m.%y")

# Maximum number of points plotted per curve. Keeps the payload small and the SVG
# readable; the curve is sampled evenly across the project window.
_MAX_CURVE_POINTS = 45

# Days of lateness beyond which extra days stop increasing an activity's priority
# score. See rank_critical_activities() for why this cap exists.
_LATENESS_CAP_DAYS = 90


# ==================== parsing helpers ====================

def parse_date(value):
    """Parse a stored date string into a date, or return None.

    Tolerates empty strings, 'N/A', free text and unexpected formats -- anything
    unparseable is simply excluded from the analytics rather than raising.
    """
    if not value:
        return None
    text = str(value).strip()
    if not text or text.upper() in {"N/A", "NA", "-", "TBD", "NIL", "NONE"}:
        return None
    for fmt in _DATE_FORMATS:
        try:
            return datetime.strptime(text, fmt).date()
        except ValueError:
            continue
    return None


def parse_number(value):
    """Parse a currency/number-ish string into a float, or return None.

    Strips currency symbols, commas and spaces so '₹ 3,40,000' and '340000' both work.
    """
    if value is None:
        return None
    text = str(value).strip()
    if not text or text.upper() in {"N/A", "NA", "-", "NIL", "NONE"}:
        return None
    cleaned = "".join(ch for ch in text if ch.isdigit() or ch in ".-")
    if not cleaned or cleaned in {"-", ".", "-."}:
        return None
    try:
        return float(cleaned)
    except ValueError:
        return None


def _ramp(current, start, finish):
    """Linear 0..1 completion fraction of a window at `current`.

    Zero-length windows are treated as a step: complete on/after the finish date.
    """
    if start is None or finish is None:
        return 0.0
    if finish <= start:
        return 1.0 if current >= finish else 0.0
    if current <= start:
        return 0.0
    if current >= finish:
        return 1.0
    return (current - start).days / (finish - start).days


def _clamp(value, low=0.0, high=100.0):
    return max(low, min(high, value))


# ==================== per-activity normalisation ====================

def _activity_rows(events):
    """Normalise Event rows into the plain dicts the curve maths works on.

    Cancelled activities are dropped. Weight falls back to the planned window length
    when `duration` is missing or nonsensical, and finally to 1.
    """
    rows = []
    for event in events:
        status = (event.status or "Planned").strip()
        if status in constants.EVENT_EXCLUDED_STATUSES:
            continue

        planned_start = parse_date(event.planned_start)
        planned_finish = parse_date(event.planned_finish)
        actual_start = parse_date(event.actual_start)
        actual_finish = parse_date(event.actual_finish)

        try:
            duration = int(event.duration or 0)
        except (TypeError, ValueError):
            duration = 0
        if duration <= 0 and planned_start and planned_finish:
            duration = max((planned_finish - planned_start).days, 1)
        weight = max(duration, 1)

        # Derive a missing planned_finish from start + duration so partially filled
        # rows still contribute to the baseline instead of silently reading as zero.
        if planned_start and not planned_finish:
            planned_finish = planned_start + timedelta(days=weight)

        try:
            criticality = int(event.criticality_rating or 1)
        except (TypeError, ValueError):
            criticality = 1
        criticality = max(1, min(5, criticality))

        try:
            progress = int(getattr(event, "progress_pct", 0) or 0)
        except (TypeError, ValueError):
            progress = 0
        progress = int(_clamp(progress))

        if status in constants.EVENT_DONE_STATUSES:
            progress = 100

        rows.append({
            "name": event.event_name,
            "status": status,
            "planned_start": planned_start,
            "planned_finish": planned_finish,
            "actual_start": actual_start,
            "actual_finish": actual_finish,
            "duration": duration,
            "weight": weight,
            "criticality": criticality,
            "progress_pct": progress,
            "remarks": event.remarks or "",
        })
    return rows


def _planned_fraction(row, on_date):
    return _ramp(on_date, row["planned_start"], row["planned_finish"])


def _actual_fraction(row, on_date, today):
    """Fraction of this activity actually achieved as at `on_date`."""
    if row["status"] in constants.EVENT_DONE_STATUSES:
        finish = row["actual_finish"] or row["planned_finish"]
        start = row["actual_start"] or row["planned_start"]
        if finish is None:
            # Completed but undated: credit it in full from today backwards.
            return 1.0 if on_date >= today else 0.0
        if on_date >= finish:
            return 1.0
        return _ramp(on_date, start, finish)

    start = row["actual_start"]
    if start is None or on_date < start:
        return 0.0

    # Work in flight: ramp from actual_start up to the recorded progress at today.
    target = row["progress_pct"] / 100.0
    if today <= start:
        return target
    return target * _ramp(on_date, start, today)


# ==================== S-curve construction ====================

def build_s_curves(events, today=None):
    """Return the planned and actual cumulative-progress series for a project.

    Result shape:
        {
          "points":  [{"date": "YYYY-MM-DD", "planned": float, "actual": float|None}, ...],
          "planned_today": float, "actual_today": float,
          "variance": float, "spi": float|None,
          "has_data": bool, "today": "YYYY-MM-DD",
        }
    `actual` is None for sample dates in the future, so the front end can stop the
    current curve at today rather than drawing it flat along the axis.
    """
    today = today or date.today()
    rows = _activity_rows(events)
    empty = {
        "points": [], "planned_today": 0.0, "actual_today": 0.0, "variance": 0.0,
        "spi": None, "has_data": False, "today": today.isoformat(),
        "start": None, "end": None,
    }
    if not rows:
        return empty

    total_weight = sum(r["weight"] for r in rows)
    if total_weight <= 0:
        return empty

    # Project window: earliest known start to latest known finish (and at least today,
    # so the "you are here" marker is always inside the plotted range).
    starts = [d for r in rows for d in (r["planned_start"], r["actual_start"]) if d]
    finishes = [d for r in rows for d in (r["planned_finish"], r["actual_finish"]) if d]
    if not starts or not finishes:
        return empty

    start = min(starts)
    end = max(max(finishes), today)
    if end <= start:
        end = start + timedelta(days=1)

    span_days = (end - start).days
    step = max(1, span_days // (_MAX_CURVE_POINTS - 1))

    sample_dates = []
    cursor = start
    while cursor < end:
        sample_dates.append(cursor)
        cursor += timedelta(days=step)
    sample_dates.append(end)
    # Guarantee today is an actual plotted vertex so the curves meet the marker exactly.
    if start <= today <= end and today not in sample_dates:
        sample_dates.append(today)
    sample_dates = sorted(set(sample_dates))

    points = []
    for sample in sample_dates:
        planned = sum(_planned_fraction(r, sample) * r["weight"] for r in rows) / total_weight * 100.0
        if sample <= today:
            actual = sum(_actual_fraction(r, sample, today) * r["weight"] for r in rows) / total_weight * 100.0
            actual = round(_clamp(actual), 2)
        else:
            actual = None
        points.append({
            "date": sample.isoformat(),
            "planned": round(_clamp(planned), 2),
            "actual": actual,
        })

    planned_today = sum(_planned_fraction(r, today) * r["weight"] for r in rows) / total_weight * 100.0
    actual_today = sum(_actual_fraction(r, today, today) * r["weight"] for r in rows) / total_weight * 100.0
    planned_today = round(_clamp(planned_today), 2)
    actual_today = round(_clamp(actual_today), 2)

    spi = round(actual_today / planned_today, 3) if planned_today > 0 else None

    return {
        "points": points,
        "planned_today": planned_today,
        "actual_today": actual_today,
        "variance": round(actual_today - planned_today, 2),
        "spi": spi,
        "has_data": True,
        "today": today.isoformat(),
        "start": start.isoformat(),
        "end": end.isoformat(),
    }


# ==================== health / status classification ====================

def classify_health(variance):
    """Map schedule variance (percentage points) to a health band."""
    if variance is None:
        return {"label": "No Baseline", "level": "unknown"}
    if variance < constants.SCHEDULE_VARIANCE_CRITICAL:
        return {"label": "Critical", "level": "critical"}
    if variance < constants.SCHEDULE_VARIANCE_AT_RISK:
        return {"label": "At Risk", "level": "warning"}
    if variance < -constants.SCHEDULE_VARIANCE_DEADBAND:
        return {"label": "Slightly Behind", "level": "caution"}
    if variance > constants.SCHEDULE_VARIANCE_DEADBAND:
        return {"label": "Ahead of Plan", "level": "good"}
    return {"label": "On Track", "level": "good"}


# ==================== critical activity ranking ====================

def rank_critical_activities(events, today=None, limit=None):
    """Rank activities by how much attention they need, most urgent first.

    The score is a transparent, additive rule -- not a model output -- so any figure
    on screen can be explained and defended:

        days overdue      x 1.2, counted up to 90   -> max 108
        days late to start x 1.0, counted up to 90  -> max  90
        criticality (1-5) x 20                      -> max 100
        progress shortfall x 0.8                    -> max  80
        + 15 flat if the status is explicitly Delayed

    The 90-day caps matter. Without them the score collapses into "days late" and
    nothing else: an activity 267 days overdue would score 534 on that term alone,
    which no criticality rating could ever offset, so a criticality-2 activity would
    outrank a criticality-5 one purely for being older. Past roughly a quarter, an
    activity is already maximally late and the exact day count stops carrying useful
    information -- what should decide priority from there is how much the activity
    matters and how far behind its own baseline it is. Capping keeps all four terms
    in the same order of magnitude so each can actually influence the ordering.

    Completed activities score 0 and are excluded.
    """
    today = today or date.today()
    rows = _activity_rows(events)
    ranked = []

    for row in rows:
        if row["status"] in constants.EVENT_DONE_STATUSES:
            continue

        reasons = []
        score = 0.0

        planned_finish = row["planned_finish"]
        overdue_days = 0
        if planned_finish and today > planned_finish:
            overdue_days = (today - planned_finish).days
            score += min(overdue_days, _LATENESS_CAP_DAYS) * 1.2
            reasons.append(f"{overdue_days} day(s) past planned finish")

        late_start_days = 0
        planned_start = row["planned_start"]
        if planned_start and not row["actual_start"] and today > planned_start:
            late_start_days = (today - planned_start).days
            score += min(late_start_days, _LATENESS_CAP_DAYS) * 1.0
            reasons.append(f"not started, {late_start_days} day(s) after planned start")

        score += row["criticality"] * 20.0
        if row["criticality"] >= constants.HIGH_CRITICALITY_THRESHOLD:
            reasons.append(f"high criticality rating ({row['criticality']}/5)")

        planned_pct = _planned_fraction(row, today) * 100.0
        actual_pct = _actual_fraction(row, today, today) * 100.0
        shortfall = max(0.0, planned_pct - actual_pct)
        score += shortfall * 0.8
        if shortfall >= 10:
            reasons.append(f"{shortfall:.0f} points behind its own baseline")

        if row["status"] == "Delayed":
            score += 15.0
            reasons.append("flagged Delayed")

        if not reasons:
            reasons.append("on schedule")

        ranked.append({
            "name": row["name"],
            "status": row["status"],
            "criticality": row["criticality"],
            "planned_start": row["planned_start"].isoformat() if row["planned_start"] else "",
            "planned_finish": planned_finish.isoformat() if planned_finish else "",
            "actual_start": row["actual_start"].isoformat() if row["actual_start"] else "",
            "progress_pct": row["progress_pct"],
            "planned_pct": round(planned_pct, 1),
            "shortfall": round(shortfall, 1),
            "overdue_days": overdue_days,
            "late_start_days": late_start_days,
            "score": round(score, 1),
            "reasons": reasons,
        })

    ranked.sort(key=lambda r: (-r["score"], r["name"]))
    return ranked[:limit] if limit else ranked


# ==================== blockers ====================

def find_blockers(project):
    """Prerequisites and regulatory approvals currently in a blocking state."""
    blockers = []
    for prereq in project.prerequisites.all():
        if (prereq.status or "").strip() in constants.PREREQUISITE_BLOCKING_STATUSES:
            blockers.append({
                "kind": "Prerequisite",
                "name": prereq.type,
                "status": prereq.status,
                "remarks": prereq.remarks or "",
            })
    for approval in project.approvals.all():
        if (approval.status or "").strip() in constants.APPROVAL_BLOCKING_STATUSES:
            blockers.append({
                "kind": "Approval",
                "name": approval.approval_type,
                "status": approval.status,
                "remarks": f"Dated {approval.date}" if approval.date and approval.date != "N/A" else "",
            })
    return blockers


# ==================== cost ====================

def cost_summary(project, progress_pct):
    """Compare money spent against work done.

    A project 30% complete that has spent 70% of budget is burning faster than it is
    progressing. `overrun_points` is that gap in percentage points; positive means
    spending is running ahead of physical progress.
    """
    budget = parse_number(project.budget)
    spent = parse_number(project.actual_expenditure)

    summary = {
        "budget": budget,
        "spent": spent,
        "burn_pct": None,
        "overrun_points": None,
        "flag": False,
        "has_data": budget is not None and budget > 0 and spent is not None,
    }
    if not summary["has_data"]:
        return summary

    burn_pct = spent / budget * 100.0
    summary["burn_pct"] = round(burn_pct, 1)
    summary["overrun_points"] = round(burn_pct - progress_pct, 1)
    summary["flag"] = burn_pct > progress_pct + constants.COST_OVERRUN_TOLERANCE * 100
    return summary


# ==================== forecast ====================

def forecast_completion(curves, project, today=None):
    """Project a likely finish date by extrapolating the achieved progress rate.

    If work has been running at 70% of the planned rate (SPI 0.7), the remaining
    work is assumed to take proportionally longer. Returns None when there isn't
    enough signal (no baseline, nothing started, or already complete).
    """
    today = today or date.today()
    if not curves["has_data"] or curves["spi"] is None or curves["spi"] <= 0:
        return None
    if curves["actual_today"] >= 99.95:
        return None

    planned_end = parse_date(project.completion_date)
    if planned_end is None and curves["end"]:
        planned_end = parse_date(curves["end"])
    if planned_end is None:
        return None

    remaining_days = (planned_end - today).days
    if remaining_days <= 0:
        remaining_days = 0

    # Remaining planned duration stretched by how far off the pace the project is.
    stretch = 1.0 / curves["spi"]
    stretch = min(stretch, 5.0)  # cap so a near-zero SPI doesn't produce absurd dates
    forecast_days = int(round(remaining_days * stretch))
    forecast_date = today + timedelta(days=forecast_days)
    slip_days = (forecast_date - planned_end).days

    return {
        "planned_completion": planned_end.isoformat(),
        "forecast_completion": forecast_date.isoformat(),
        "slip_days": slip_days,
        "is_late": slip_days > 0,
    }


# ==================== top-level assembly ====================

def analyse_project(project, today=None):
    """Full deterministic analytics bundle for a single project."""
    today = today or date.today()
    events = list(project.events.all())

    curves = build_s_curves(events, today=today)
    critical = rank_critical_activities(events, today=today)
    blockers = find_blockers(project)
    cost = cost_summary(project, curves["actual_today"])
    forecast = forecast_completion(curves, project, today=today)
    health = classify_health(curves["variance"] if curves["has_data"] else None)

    counted = [e for e in events if (e.status or "") not in constants.EVENT_EXCLUDED_STATUSES]
    status_counts = {}
    for event in events:
        key = (event.status or "Planned").strip() or "Planned"
        status_counts[key] = status_counts.get(key, 0) + 1

    equipment = list(project.equipment_items.all())
    equipment_by_category = {}
    for item in equipment:
        equipment_by_category[item.category] = equipment_by_category.get(item.category, 0) + item.count

    return {
        "project": project,
        "name": project.name,
        "curves": curves,
        "health": health,
        "critical_activities": critical,
        "top_critical": critical[:5],
        "blockers": blockers,
        "cost": cost,
        "forecast": forecast,
        "activity_total": len(counted),
        "activity_status_counts": status_counts,
        "equipment_units": sum(i.count for i in equipment),
        "equipment_by_category": equipment_by_category,
        "today": today.isoformat(),
    }


def analyse_portfolio(projects, today=None):
    """Aggregate analytics across every project, for the portfolio dashboard."""
    today = today or date.today()
    rows = []
    for project in projects:
        analysis = analyse_project(project, today=today)
        rows.append({
            "name": project.name,
            "category": project.project_category or "Uncategorised",
            "nature": project.nature_of_project or "",
            "area_unit": project.area_unit or "",
            "planned_pct": analysis["curves"]["planned_today"],
            "actual_pct": analysis["curves"]["actual_today"],
            "variance": analysis["curves"]["variance"],
            "spi": analysis["curves"]["spi"],
            "health": analysis["health"],
            "blocker_count": len(analysis["blockers"]),
            "critical_count": sum(
                1 for a in analysis["critical_activities"]
                if a["overdue_days"] > 0 or a["late_start_days"] > 0 or a["status"] == "Delayed"
            ),
            "budget": analysis["cost"]["budget"],
            "spent": analysis["cost"]["spent"],
            "cost_flag": analysis["cost"]["flag"],
            "forecast": analysis["forecast"],
            "has_data": analysis["curves"]["has_data"],
        })

    with_data = [r for r in rows if r["has_data"]]
    total_budget = sum(r["budget"] for r in rows if r["budget"])
    total_spent = sum(r["spent"] for r in rows if r["spent"])

    health_counts = {"good": 0, "caution": 0, "warning": 0, "critical": 0, "unknown": 0}
    for row in rows:
        health_counts[row["health"]["level"]] = health_counts.get(row["health"]["level"], 0) + 1

    by_category = {}
    for row in rows:
        bucket = by_category.setdefault(row["category"], {"count": 0, "variance_sum": 0.0, "budget": 0.0})
        bucket["count"] += 1
        bucket["variance_sum"] += row["variance"]
        bucket["budget"] += row["budget"] or 0.0
    for bucket in by_category.values():
        bucket["avg_variance"] = round(bucket["variance_sum"] / bucket["count"], 1)

    avg_variance = round(sum(r["variance"] for r in with_data) / len(with_data), 2) if with_data else 0.0
    avg_planned = round(sum(r["planned_pct"] for r in with_data) / len(with_data), 1) if with_data else 0.0
    avg_actual = round(sum(r["actual_pct"] for r in with_data) / len(with_data), 1) if with_data else 0.0

    return {
        "rows": sorted(rows, key=lambda r: r["variance"]),
        "project_count": len(rows),
        "avg_variance": avg_variance,
        "avg_planned": avg_planned,
        "avg_actual": avg_actual,
        "health_counts": health_counts,
        "at_risk_count": health_counts["warning"] + health_counts["critical"],
        "total_budget": total_budget,
        "total_spent": total_spent,
        "burn_pct": round(total_spent / total_budget * 100, 1) if total_budget else None,
        "total_blockers": sum(r["blocker_count"] for r in rows),
        "by_category": by_category,
        "today": today.isoformat(),
    }
